function zdot = CartPoleEOM(t,in2)
%CartPoleEOM
%    ZDOT = CartPoleEOM(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    08-Feb-2024 16:38:59

lam1 = in2(5);
lam2 = in2(6);
lam3 = in2(7);
lam4 = in2(8);
th = in2(2);
thd = in2(4);
xd = in2(3);
t2 = cos(th);
t3 = sin(th);
t4 = thd.^2;
t7 = lam3.*1.0e+1;
t5 = t2.^2;
t6 = t3.^2;
t9 = lam4.*t2.*2.0e+1;
t13 = t3.*t4.*(3.0./2.0e+1);
t17 = t3.*1.2753e+1;
t19 = t2.*t3.*2.943;
t8 = t5.*3.0;
t10 = -t9;
t11 = t5.*(3.0./1.0e+1);
t12 = t5.*(3.0./2.0e+1);
t16 = t2.*t13;
t14 = t8-1.3e+1;
t15 = t7+t10;
t20 = t11-1.3e+1./1.0e+1;
t21 = t12-1.3e+1./2.0e+1;
t18 = 1.0./t14;
t22 = 1.0./t20;
t23 = 1.0./t21;
t24 = t15.*t18;
t25 = t2.*t24;
t26 = t13+t19+t24;
t27 = t16+t17+t25;
zdot = [xd;thd;-t22.*t26;t23.*t27;0.0;-lam4.*t23.*(t2.*1.2753e+1-t4.*t6.*(3.0./2.0e+1)+t4.*t12-t3.*t24)+lam3.*t22.*(t5.*2.943-t6.*2.943+t2.*t4.*(3.0./2.0e+1))+lam3.*t2.*t3.*t22.^2.*t26.*(3.0./5.0)-lam4.*t2.*t3.*t23.^2.*t27.*(3.0./1.0e+1);-lam1;-lam2+lam3.*t3.*t22.*thd.*(3.0./1.0e+1)-lam4.*t2.*t3.*t23.*thd.*(3.0./1.0e+1)];
end
