function u0 = Find_u0(in1)
%Find_u0
%    U0 = Find_u0(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    08-Feb-2024 16:39:00

lam3 = in1(7);
lam4 = in1(8);
th = in1(2);
t2 = cos(th);
u0 = (lam3.*1.0e+1-lam4.*t2.*2.0e+1)./(t2.^2.*3.0-1.3e+1);
end
